version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: fitness_postgres
    environment:
      POSTGRES_DB: fitness
      POSTGRES_USER: fitness_user
      POSTGRES_PASSWORD: fitness_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  generator:
    build: ./generator
    container_name: fitness_generator
    depends_on:
      - postgres
  
  redis:
    image: redis:7
    container_name: redash_redis

  redash:
    image: redash/redash:latest
    container_name: redash
    depends_on:
      - postgres
      - redis
    environment:
      REDASH_DATABASE_URL: postgres://fitness_user:fitness_password@postgres:5432/fitness
      REDASH_REDIS_URL: redis://redis:6379/0
    ports:
      - "5000:5000"
  
  redash_worker:
    image: redash/redash:latest
    depends_on:
      - redash
      - redis
    environment:
      REDASH_DATABASE_URL: postgres://fitness_user:fitness_password@postgres:5432/fitness
      REDASH_REDIS_URL: redis://redis:6379/0
    command: worker

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: fitness_jupyter
    ports:
      - "8888:8888"
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - postgres
 
volumes:
  postgres_data:
